apiVersion: v1
kind: Service
metadata:
  name: ${masterNodeName} # headless service name, will be used to be part of the DNS name
  namespace: ${namespace}
  labels:
    app: ${masterNodeName}
spec:
  clusterIP: None  #headless service
  ports:
    - name: network #network port
      port: 10000 
      targetPort: 10000 # The best way should be determined by system but here we just fix it
    - name: rpc
      port: 10001   #rpc port
      targetPort: 10001 # The best way should be determined by system but here we just fix it
  selector:
    app: ${masterNodeName} # should match the selector.matchLabels  for StatefulSet  which is 'app: ${masterNodeName}'