apiVersion: apps/v1  #Deployment and StatefulSet is defined in apps/v1 not in corev1
kind: StatefulSet
metadata:
  name: ${masterNodeName} #StatefulSet name
  namespace: ${namespace}   #should be int the same namespace as headless service
  labels:
    app: ${masterNodeName}
spec:
  serviceName: ${masterNodeName} #Headless Service name, will be used to generate the pod name
  replicas: 1         #we only need 1 master
  podManagementPolicy: Parallel     #default is OrderedReady
  selector:
    matchLabels:
      app: ${masterNodeName}  #used to identify the service
  template:
    metadata:
      labels:
        app: ${masterNodeName}
    spec:
      dnsConfig: {}
      dnsPolicy: ClusterFirst    
      restartPolicy: Always
      schedulerName: default-scheduler       
      terminationGracePeriodSeconds: 10
      containers:
        - name: multichain-${masterNodeName}  
          image: 127.0.0.1:5000/menglong567:multichain-master
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash","/root/setup-master.sh"]
          args: ["/home/multichain-${masterNodeName}/data","${chainName}","10000","10001"] ##datadir chainname port rpcport
          ports:
            - name: network
              containerPort: 10000 
            - name: rpc
              containerPort: 10001            
          volumeMounts:
            - mountPath: /home/multichain-${masterNodeName}/data  #directory in docker container    
              name: data
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "${memoryRequest}Mi" # ${memoryRequest}
              cpu: "${cpuRequest}m" # ${cpuRequest}
            limits:
              memory: "${memoryLimit}Mi" #${memoryLimit}
              cpu: "${cpuLimit}m"    # ${cpuLimit}
      volumes:
      - name: data
        hostPath:
          path: /home/multichain-${masterNodeName}-k8s/data  # directory location on host
          type: DirectoryOrCreate  # this could be Directory / DirectoryOrCreate   