apiVersion: v1
kind: Service
metadata:
  name: ${masterNodeName}-nodeport #nodeport service name
  namespace: ${namespace}
  labels:
    app: ${masterNodeName}-nodeport
spec:
  type: NodePort
  ports:
  - port: 10000  #network port
    nodePort: 31000 # The best way should be determined by system but here we just fix it
    name: network
  - port: 10001  #rpc port
    nodePort: 31001 # The best way should be determined by system but here we just fix it
    name: rpc
  selector:
    app: ${masterNodeName}   # should match the selector.matchLabels  for StatefulSet which is 'app: ${masterNodeName}'