#setup master
version: '3'
services:

  multichain-master:
    build:
      context: ./master
    image: menglong567:multichain-master
    ports:
      - "10000:10000" #default-network-port
      - "10001:10001" #default-rpc-port
    #datadir chainname port rpcport
    entrypoint: ["/bin/bash","/root/setup-master.sh","/home/multichain-master/data","DemoChain","10000","10001"]
    container_name: multichain-master
    volumes:
      - /home/multichain-master/data:/home/multichain-master/data
    networks:
       multichain-network:
          ipv4_address: 172.30.0.2
    ulimits:
       nproc: 65535
       nofile:
         soft: 20000
         hard: 40000   
    
networks:
   multichain-network:
      ipam:
         driver: default 
         config:
         - subnet: 172.30.0.0/16        